#!/bin/sh

# filter() { mpc | sed "/^volume:/d;s/\\&/&amp;/g;s/\\[paused\\].*/⏸/g;/\\[playing\\].*/d" | paste -sd ' ' -;}
filter() {
	artist=$(playerctl --player cmus,vlc,%any metadata | sed -n "/artist/p" | awk '{for(i=3;i<=NF;i++){printf "%s ", $i}}{printf"\n"}');
	title=$(playerctl --player cmus,vlc,%any metadata | sed -n "/title/p" | awk '{for(i=3;i<=NF;i++){printf "%s ", $i}}{printf"\n"}');
	status=$(playerctl --player cmus,vlc,%any status)

	if [[ $status == "Paused" ]]
	then
		echo -n ⏸️
	fi
	echo "$artist - $title";
}

pidof -x sb-mpdup >/dev/null 2>&1 || sb-mpdup >/dev/null 2>&1 &

case $BLOCK_BUTTON in
	1) playerctl --player cmus,vlc,%any status | filter ; setsid -f "$TERMINAL" -e cmus ;;  # right click, pause/unpause
	2) playerctl --player cmus,vlc,%any play-pause | filter ;;  # right click, pause/unpause
	3) playerctl --player cmus,vlc,%any status | filter ; notify-send "🎵 Music module" "\- Shows playerctl song playing.
- ⏸ when paused.
- Left click opens ncmpcpp.
- Middle click pauses.
- Scroll changes track.";;  # right click, pause/unpause
	4) playerctl --player cmus,vlc,%any previous | filter ;;  # scroll up, previous
	5) playerctl --player cmus,vlc,%any next | filter ;;  # scroll down, next
	6) playerctl --player cmus,vlc,%any status | filter ; "$TERMINAL" -e "$EDITOR" "$0" ;;
	*) playerctl --player cmus,vlc,%any status | filter ;;
esac
